repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/akbiggs/docformatter
    rev: stable
    hooks:
    - id: docformatter-venv

